### ISSUE TITLE
Redstone Not Working After Fill

### ISSUE THREAD

**Issue by GeekzGamingz** [Brettflan/WorldBorder#100]
Hi there, ever since filling in my world with worldborder, all of my redstone is ticking very slow and now causes crashes up some being used.

**Comment by Brettflan** [comment]
Running Fill simply has the server generate the desired chunks, nothing more.

If your redstone problem is while Filling is still happening or for instance a Dynmap map is being generated, perhaps it will improve after completion. Also, if the Fill process is still going, you could try cancelling it and running it again at a lower frequency if you're wanting to play while it's Filling.

If neither of the above is true, try restarting your server (one of the basic things to try when troubleshooting a Minecraft server).

If that also doesn't work, your problem is with something else regardless.

**Comment by GeekzGamingz** [comment]
Well, while generated a large world with World Border (10000 block radius) it crashed several times due to overloading the CPU since it was such a large area. Is it possible that during that process chunks were corrupted? I'm running 1.13.1 by the way. Also, my world is still doing this even without any plugins at all. I've been troubleshooting for several days and have reset the server several times during that process trying different approaches.

**Comment by Brettflan** [comment]
1.13 builds of Spigot are of course still dev builds and not stable, so potentially really nasty bugs are very possible. Particularly if you were using a world originally created in an older version of Minecraft (world breaking conversion problems in the current builds, apparently), but even if not, running into other bugs is likely. 

Do you have a crash log?

For reference, here's a list of current open Spigot issues regarding redstone:
https://hub.spigotmc.org/jira/browse/SPIGOT-141?jql=text%20~%20%22redstone%22
One of those might be related to your problem.

**Comment by GeekzGamingz** [comment]
Nah, it's been 1.13 from day 1 when it first came out. My current theory is lighting. Lighting can dramatically changed and is very buggy at this time. So my current theory is that World Border generated a lot of chunks which in turn triggered some bad lighting issues especially on crashes. I'm current running a full world CleanLight to see if that fixes my problem. In any case, thank you for your assistance.

**Comment by Brettflan** [comment]
Definitely unusual.

If you do find out more specifically what the problem is, I'd be curious to know.

**Comment by GeekzGamingz** [comment]
The problem is resolved. After debugging on my local server I found that it was a conflict between three plugins updated very recently after the World Border. I apologize for any inconvenience I may have caused and thank you for your help and suggestions on this matter!
