### ISSUE TITLE
Lag on 1.13.1

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Brettflan/WorldBorder#104]
Without even loading chunks the plugin causes severe tick lag. I know in 1.13 chunk loads are changed, maybe it has something to do with that. Once i remove the plugin, my server runs spick and span.

**Comment by SnakeDaoust1232** [comment]
Maybe thats the reason my server is lagging. Im not using the dev version. Is there a link?

**Comment by Brettflan** [comment]
There's no download for a 1.13.1 build, but you can of course build it yourself if you really want. The latest release was working fine for me though (I did test it in 1.13.1), as far as performance goes, and there haven't been any performance changes since then.

And again, based on how the plugin works, I don't see how it would be causing performance problems in the first place except when running a Fill or possibly a Trim. Other than those functions, it should have no noticeable performance impact on a server, which is why I find it hard to believe it's causing you such problems.
