### ISSUE TITLE
Fill crash

### ISSUE THREAD

**Issue by Misio12320** [Brettflan/WorldBorder#124]
Hello. When I fill my world the server crash/ plugin crash. 
[2019-03-31-3.log](https://github.com/Brettflan/WorldBorder/files/3026515/2019-03-31-3.log) here's log from paper, and here log from https://pastebin.com/A4DLXWXR from spigot

**Comment by Brettflan** [comment]
The error is the same in both:
`Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 97 151`

Not the fault of WorldBorder, as per usual.

Looks like your world has a corrupt region file. Most likely caused by running out of disk space while the world was generating, but it could have been caused by other things.

A quick search led to:
http://koastal.world/exception-generating-new-chunk-a-detailed-fix-method/

**Comment by Misio12320** [comment]
Great, I saw today bad chunks while traveling the world and. How to fix that? What I have to do? My backup from yesterday have 13.21GB and todays backup is 5.47...

**Comment by Misio12320** [comment]
and I have a issue, when I join server im getting teleported somewhere coords 8.5 y 8.5 and I have blue screen I mean I have clean chunks nothing visible, 5 seconds later I'm getting kicked with "disconnected" isn't that happen by WorldBorder? + when I have done my worldborder fill after restart I'm getting ~45% like before fill...

**Comment by Brettflan** [comment]
My comment above pointed to a link detailing a fix.
