### ISSUE TITLE
Bounce back sometimes sends you to world spawn.

### ISSUE THREAD

**Issue by andrewkm** [Brettflan/WorldBorder#178]
The bounceback sometimes sends you back to the world spawn. This is all dependent on your surroundings, I'm assuming as a safety precaution of sorts.

Example: https://youtu.be/XHYiS5RskHA

Any way to fix this so instead it looks for a safe spot as close to you as possible instead of just launching you to the worlds spawn?

**Comment by dcoshea** [comment]
This overlaps with issue #115, because the "Players getting teleported below y=0" mentioned in the title of that issue is due to spawn being 0, 0, 0.

**Comment by dcoshea** [comment]
The commit message shown above has some details of the circumstances in which I hit this issue.  I hit this issue with version 1.9.10 beta on Spigot 1.15.2.  I can confidently say that I didn't hit this issue with version 1.8.7 on Spigot 1.11.2 because I tested with the same build in the same location in the same world with both versions.
