### ISSUE TITLE
Worldborder extending, dynmap not updating correctly

### ISSUE THREAD

**Issue by Sikatsu** [Brettflan/WorldBorder#78]
So I just /wb radius +2500 and I've used /wb fill, however this is how my dynmap looks like: http://mc.villagercraft.eu:8050/

How can I fix the black dots and squares? Why didn't it render actually?

**Comment by Brettflan** [comment]
Looks like DynMap got behind on rendering. Try doing a fullrender in DynMap, but whatever the case, it's not an problem with WorldBorder.

**Comment by Sikatsu** [comment]
Alright thanks, that should work out I guess.

**Comment by Sikatsu** [comment]
If I do a fullrender while a big part of the map was already rendered, would that cause performance issues? (because the sqlite file increases, currently 17GB)

**Comment by wioxjk** [comment]
@Brettflan 
I have got the same issue in many of environments I have set up before.
Setting a round border of 10000blocks. And do a wb fill, wait many hours to complete it.

Doing a dynmap fullrender in many cases shows black chunks.
However, increasing the "freq" does also increase the number of "black" chunks showing on dynmap.

So therefore, I think this is highly related to WorldBorder. (or maybee performance issues during fill)

**Comment by Brettflan** [comment]
Generating chunks is probably the most demanding process in Minecraft, so of course performance can be hit during the process, and of course it is "related" to WorldBorder's Fill process by extension. If you increase the Fill frequency, that makes it even worse, and in fact often counter-intuitively can often lead to slower world generation. Add to that the fact that Dynmap trying to map out chunks is rather processor-intensive as well, and yes, the map produced by Dynmap can sometimes need to be fixed. Sometimes you need to clear the map entirely in Dynmap before doing another fullrender.

Smartest practice would probably be to suspend mapping by Dynmap until the Fill process is completed.

**Comment by Sikatsu** [comment]
Since I changed from hosts, I've reset my dynmap.

First I did /wb fill, afterwards I did /dynmap fullrender. The frequency was default, yet it still shows these black squares.

**Comment by Brettflan** [comment]
Just a fullrender doesn't always cut it, you sometimes need to wipe the map first. I forget the command in Dynmap to do so, but there is one.

**Comment by Sikatsu** [comment]
The map was wiped? I deleted the database.

**Comment by Brettflan** [comment]
The images aren't stored in the database.

**Comment by wioxjk** [comment]
@Brettflan 
I never run dynmap render and wb fill at the same time.
However, completly deleting the dynmap folder and re-render the map does not remove the black areas.

That's why I suspect "issue" with worldborder.
However, since I changed CPU to a more powerful Xeon the issue is almost non-existant.

**Comment by Brettflan** [comment]
Interesting, this might be a relatively new issue, then. Previously people have gotten this problem, with parts of their Dynmap map not rendering due to their server being overwhelmed, and wiping the map and doing a fullrender would fix it, as it was solely a mapping issue.

If you run the Fill process again (preferably with default frequency), do you get any changes? If the black chunks were not generated somehow due to problems within the CraftBukkit chunk loading process (which has never been an issue through the years, but maybe it's a new thing), running the Fill process again would ensure that they are generated as the process checks for the existence of every chunk.
If running Fill again makes any of those black chunks go away, then this may indeed be a new-ish issue with CraftBukkit/Spigot.

**Comment by wioxjk** [comment]
@Brettflan 
Doing one or two more wb fill does solve the problem.

I can do some more testing also to really ensure that this is a problem.
