### ISSUE TITLE
[Feature]: Visual Border

### ISSUE THREAD

**Issue by DovahDoVolom** [Brettflan/WorldBorder#81]
I know that the in-game world border gives a visual, but it doesn't have the ability to be circular. It it possible to use particles with your plugin to give a visual of the world border? I know it can be veeery resource heavy if the whole world border was covered in particles, but that could be solved by displaying the particles within the certain radius of a player.

**Comment by Brettflan** [comment]
Not a bad idea. There would certainly be a larger resource requirement, but done right, it probably wouldn't be too bad.

However, I'm no longer actively developing the plugin at this point, only handling compatibility updates and potential bugfixes.
The source is of course available here on GitHub, so that anyone else is free to work on something like that. I might even be able to set aside a little time to help with implementing it if anyone were interested enough to give it a shot, but I don't really have the time or desire to implement everything that would be needed myself.
