### ISSUE TITLE
[BAG] Disable permissions when saving changes

### ISSUE THREAD

**Issue by DarkFort** [Brettflan/WorldBorder#90]
Recently I noticed that [while saving changes](https://i.imgur.com/Hmoooky.jpg), when there is a peace process, you can put blocks in the region. The players took advantage of this and built a spawn.

**Comment by Brettflan** [comment]
I don't know what you mean by "peace process".

When the Fill process says "Saving the world to disk", it is using Bukkit's World.save() method. If that is somehow allowing block placement by someone in a location where they shouldn't be allowed, the problem is not with WorldBorder and there's nothing on WorldBorder's end that can be done about it.

**Comment by DarkFort** [comment]
Then what is the problem?

**Comment by Brettflan** [comment]
It sounds like it would be a Bukkit/Spigot problem, though it could be related to a different plugin / mod.
