### ISSUE TITLE
trees don't spawn correctly

### ISSUE THREAD

**Issue by TheCompieter** [Brettflan/WorldBorder#98]
trees don't spawn correctly in 1.13 with worldborder 
![2018-08-14_15 01 47](https://user-images.githubusercontent.com/34034571/44093276-5a3b7646-9fd3-11e8-879a-e308d9d65186.png)

**Comment by dwilley83** [comment]
Found this same issue after running /wb fill command to generate chunks before rendering dynmap. It cuts the trees off at the chunk border lines.

**Comment by dwilley83** [comment]
Issue might be with Spigot 1.13. I deleted my world folders on my test server, updated Spigot to the latest version (as of yesterday morning), and regenerated them using the same seed in the server.properties file. Used /wb fill and searched for trees that had been cut in half on the chunk borders. I only found 1 so far. The other areas that had generated the oddly generated trees in the previous world did not have them in the newly generated world. I don't know if this is coincidence or if it was something that was fixed in a version of Spigot. I will continue to search and monitor. I have dynmap rendering and it will help my search.

**Comment by Brokkonaut** [comment]
Its a general bug in minecraft 1.13 map generation (happens also in vanilla)

**Comment by TheCompieter** [comment]
thanx for confirming i hope it's fixed in 1.13.1 (i dont think so)

**Comment by dwilley83** [comment]
@Brokkonaut I had not noticed this on a minecraft 1.13 server I had made in preparation for having a 1.13 server but noticed it when I made a Spigot 1.13 test server to test plugins. It was really bad and they were everywhere. Since I had regenerated the world with the latest Spigot 1.13 I still have only found one of these trees around a 7500 x 7500 block radius map.
